# /// script
# requires-python = ">=3.11"
# ///
"""
make_index.py
=============
Regenerates SCRIPTS.md from the one-line summary in each script's docstring.

The docstrings are the real documentation in this repo -- each states a
hypothesis, a prior, and what would falsify it. This just makes them findable.
Re-run after adding a script:  python make_index.py
"""
from __future__ import annotations

import ast
import glob
import io
import os

# 🚨 KEPT LOCALLY, NOT PUBLISHED -- SO NOT INDEXED EITHER.
# These are gitignored (see .gitignore and NOTICE): they are derivatives of a
# CC BY-NC-SA 4.0 Pine script, whose ShareAlike and NonCommercial terms conflict
# with this repo's Apache 2.0 licence. SCRIPTS.md *is* committed, so without this
# set the published index would advertise two files that are not in the
# repository -- a broken link at best, and at worst a reader concluding the
# licence conflict was published rather than excluded.
#
# Every name here must also be in .gitignore. If you un-ignore one, delete it
# from here in the same change.
UNPUBLISHED = {"smart_money_flow.py", "check_smart_money_flow.py"}

GROUPS = [
    ("Core simulation & data", [
        "sim_core.py", "amt_profile.py", "sequential_fills.py",
        "build_hedge_flow.py", "smart_money_flow.py", "make_index.py",
    ]),
    ("Book scoring & config decisions", [
        "check_book_now.py", "check_trail_regression.py", "check_config_walkforward.py",
        "check_sequential_fills.py", "check_sample_invariance.py",
    ]),
    ("Screening & candidate validation", [
        "check_etf_screen.py", "check_screen_candidate.py", "check_candidate_retest.py",
        "check_scanner.py", "check_uoa_target.py",
    ]),
    ("Exit policy", [
        "check_exit_sweep.py", "check_exit_walkforward.py", "check_giveback.py",
        "check_holdtime.py", "check_strike_selection.py",
    ]),
    ("Entry gates & signal quality", [
        "check_amt.py", "check_amt_variants.py", "check_adx_dmi.py",
        "check_signal_quality.py", "check_volume_signal.py", "check_flow_accumulation.py",
        "check_hedge_participation.py", "check_hedge_signal.py",
        "check_smart_money_flow.py", "check_entry_cutoff.py", "check_hour10.py",
        "check_hour_drift.py", "check_open_delay.py",
    ]),
    ("Sizing & position policy", [
        "check_size_gate.py", "check_pileon.py", "check_scalein.py", "check_scalein_otm.py",
        "check_day_anatomy.py",
    ]),
]


def summary(path):
    try:
        doc = ast.get_docstring(ast.parse(io.open(path, encoding="utf-8").read())) or ""
    except Exception:
        return ""
    base = os.path.basename(path).lower()
    for ln in (l.strip() for l in doc.splitlines()):
        if not ln or ln.lower() == base or set(ln) <= set("=-_"):
            continue
        return ln[:110]
    return ""


def main():
    seen, out = set(), []
    out.append("# Script Index\n")
    out.append("Auto-generated by `make_index.py` from each script's docstring. "
               "The docstrings are the real documentation — each states a hypothesis, "
               "a prior, and what would falsify it.\n")
    out.append("**Read `METHODOLOGY.md` first.** Every simulation should route through "
               "`sim_core.py`; hand-rolled simulators have drifted silently twice.\n")
    for title, files in GROUPS:
        rows = [(f, summary(f)) for f in files
                if os.path.exists(f) and f not in UNPUBLISHED]
        if not rows:
            continue
        out.append(f"\n## {title}\n")
        for f, s in rows:
            seen.add(f)
            out.append(f"- **`{f}`** — {s}")
    rest = sorted(set(glob.glob("check_*.py")) - seen - UNPUBLISHED)
    if rest:
        out.append("\n## Other / older investigations\n")
        for f in rest:
            out.append(f"- `{f}` — {summary(f)}")
    io.open("SCRIPTS.md", "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"wrote SCRIPTS.md  ({len(seen) + len(rest)} scripts)")


if __name__ == "__main__":
    main()
